admins:
- lucydot
- choochoo-bot
gh-pages: true
gh-pages_branch: gh-pages
instructors:
- lucydot
project_repo: lucydot/ChooChoo-template
project_title: Choochoo template repository
questions: true
students:
- lucydot
- choochoo-bot
- sofjgnsofjgnos
votes_required: 3
web_address: https://lucydot.github.io/ChooChoo-template
